KACPER-10 added JWT user authorization
kmkcc2/express pull request #7
Opened 2023-08-28 14:32 UTC by kmkcc2

2023-08-28 15:16 UTC, FilipAlbrycht requested changes

2023-08-28 15:16 UTC, FilipAlbrycht commented on controllers/auth.controller.ts
> +  const user: IUser | any = await User.findOne({
1. IUser | null
2. I think typing should come from model, try this way

2023-08-28 15:16 UTC, FilipAlbrycht commented on controllers/auth.controller.ts
> +  const user: IUser | any = await User.findOne({
move db operations to repositories ex. users.repository.ts

2023-08-28 15:16 UTC, FilipAlbrycht commented on controllers/auth.controller.ts
> +  if (user === null) {
if (!user)

2023-08-28 15:16 UTC, FilipAlbrycht commented on controllers/auth.controller.ts
> +      .status(401)
404 instead of 401

2023-08-28 15:16 UTC, FilipAlbrycht commented on middleware/authorize.ts
> +    if (typeof authHeader === 'undefined') {
if (!authHeader)

2023-08-28 15:16 UTC, FilipAlbrycht commented on middleware/authorize.ts
> +    if (token === null) return res.status(401).send({ message: 'Unauthorized' })
if (!token)

2023-08-28 15:16 UTC, FilipAlbrycht commented on middleware/authorize.ts
> +    jwt.verify(token, SECRET, (err, user: any) => {
try to avoid typing as any

2023-08-28 15:16 UTC, FilipAlbrycht commented on middleware/authorize.ts
> +    console.log(err)
remove clg

2023-08-28 15:16 UTC, FilipAlbrycht commented on routes/auth.ts
> +  .route('/login')
you're missing request validation for login

2023-08-28 15:16 UTC, FilipAlbrycht commented on controllers/auth.controller.ts
> +        message: 'loggin in successful',
not sure if that message will have any usage ;)

2023-08-28 15:16 UTC, FilipAlbrycht commented on controllers/auth.controller.ts
> +  req: TypedRequestBody<{
looks like very generic typing, please add request validation and type request from class responsible for validation

2023-08-28 18:02 UTC, benmotyka commented on controllers/auth.controller.ts
> +import { type IUser, type TypedRequestBody } from '../common/interfaces'
warto zapoznac sie z tym jaka jest roznica miedzy import x a import type x, nie zeby tu bylo zle ale tak ogolnie

2023-08-28 18:02 UTC, benmotyka commented on controllers/auth.controller.ts
> +export const login: any = async (
raczej usunalbym any i pozwolil na type interference https://www.typescriptlang.org/docs/handbook/type-inference.html

2023-08-28 18:02 UTC, benmotyka commented on controllers/auth.controller.ts
> +  const user: IUser | any = await User.findOne({
tutaj tez imo type interference wystarczy, a swoja droga | any troche psuje sens typowania

2023-08-28 18:02 UTC, benmotyka commented on controllers/auth.controller.ts
> +  const payload = {
przy tworzeniu obiektow akurat warto je otypowac czym one maja byc

2023-08-28 18:02 UTC, benmotyka commented on controllers/auth.controller.ts
> +    const SECRET: string = process.env.ACCESS_TOKEN_SECRET as string
nie musisz oznaczac zmiennej jako string skoro ja castujesz jako string

2023-08-28 18:02 UTC, benmotyka commented on middleware/authorize.ts
> +  } catch (err: any) {
usunalbym any, generalnie staraj sie tego unikac chyba ze np korzystasz z jakiejs starej libki

2023-09-01 15:11 UTC, benmotyka2 approved these changes

2023-09-01 15:19 UTC, benmotyka approved these changes

2023-09-04 14:00 UTC, FilipAlbrycht approved these changes

2023-09-04 14:00 UTC, FilipAlbrycht commented on controllers/auth.controller.ts
> +  const user = await _userRepository.findUserByEmail(req.body.email)
tak na prawde moglbys odrazu wyszukiwac po username&password wtedy (oczywiscie po zaszyfrowanym hasle)

2023-09-04 14:00 UTC, FilipAlbrycht commented on controllers/user.controller.ts
> +    if (userUniqueEmailCheck !== null) {
if (userUniqueEmailCheck)

2023-09-11 09:58 UTC, merged