Kacper 9 verify content type middleware
kmkcc2/express pull request #8
Opened 2023-08-31 10:08 UTC by kmkcc2

2023-09-04 14:02 UTC, FilipAlbrycht requested changes

2023-09-04 14:02 UTC, FilipAlbrycht commented on middleware/verify-content-type.ts
> +    return res.status(400).send({ message: 'Invalid Content-Type header' })
415 http code jesli content type sie nie zgadza

2023-09-04 14:02 UTC, FilipAlbrycht commented on middleware/verify-content-type.ts
> +  if ((req.method !== 'GET' && req.method !== 'DELETE') && !req.is('application/json')) {
pytanie co w przypadku charsetu tzn Content-Type = application/json; charset=UTF-8

2023-09-04 14:02 UTC, FilipAlbrycht commented on server.ts
> +app.use('/users', verifyContent, authorize, userRouter)
uzyj globalnie tego middleware'a

2023-09-04 14:48 UTC, benmotyka approved these changes
mega spoko :)

2023-09-04 14:48 UTC, benmotyka commented on middleware/request-validation.ts
> +  for (const validation of validationChain) {
tutaj taki niuans ale w przypadku operacji ktorych wynik nie wplywa na nic co jest za nimi czasem lepiej jest uzyc Promise.all ze wzgledu na to ze wykonuja sie rownolegle i co do zasady dzialaja szybciej niz for const of

2023-09-04 14:48 UTC, benmotyka commented on middleware/request-validation.ts
> +  for (const validation of validationChain) {
https://stackoverflow.com/questions/45285129/any-difference-between-await-promise-all-and-multiple-await

2023-09-11 10:13 UTC, kmkcc2 commented on middleware/verify-content-type.ts
> +  if ((req.method !== 'GET' && req.method !== 'DELETE') && !req.is('application/json')) {
Testowałem w postmanie i dalej działa tak jak jest oczekiwane.

2023-09-11 12:21 UTC, merged